- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{trainer}}, duration is {{duration}}"