- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print override information
    vars:
      time: "07:15AM IST"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{trainer}}, duration is {{duration}},timings: timings are {{time}}"