- name: variable preference
  hosts: localhost
  # vars:
  #   WISH: "Good Morning from play variable"
  # vars_prompt:
  # - name: WISH
  #   prompt: enter wishes
  #   private: false
  vars_files:
  - vars.yaml     
  tasks:
  - name: check preference
    # vars:
    #   WISH: "Good Morning from task variable"
    ansible.builtin.debug:
      msg: "Hello, Good {{WISH}}"

     # 1.arguments
     # 2.task level
     # 3.file level 
     # 4.prompt
     # 5. Play
     # 6. inventory